name: habitat
channels:
  - conda-forge
  - aihabitat
dependencies:
  - python=3.9
  - habitat-sim=0.3.3
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - torch==2.5.1
      - transformers==4.57.6
      - huggingface_hub==0.36.2